# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0005_remove_carnet_imma'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet',
            name='imma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parcauto.Vehicule'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='carnets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parcauto.Carnet'),
        ),
    ]
