# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0006_auto_20170526_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparation',
            name='dateAccident',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='dateFin',
            field=models.DateField(),
        ),
    ]
