# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0007_auto_20170526_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='imma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcauto.Vehicule'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='nbPlace',
            field=models.IntegerField(verbose_name='Nombres de places'),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='dateAccident',
            field=models.DateTimeField(verbose_name="Date de l'accidnet"),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='dateFin',
            field=models.DateField(verbose_name='Date de fin de reparation'),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='natureReparation',
            field=models.CharField(max_length=25, verbose_name='Nature de la reparation'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='carnets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcauto.Carnet'),
        ),
    ]
