# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0009_auto_20170526_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='imma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='parcauto.Vehicule'),
        ),
    ]
