# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0010_auto_20170526_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='modeles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='parcauto.Modele'),
        ),
    ]
