# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0011_auto_20170526_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='anneeFabr',
            field=models.DateTimeField(),
        ),
    ]
