# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0014_auto_20170526_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='kilometrage',
            new_name='kilomatrage',
        ),
    ]
