# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0002_remove_vehicule_carnets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carnet',
            old_name='vehicules',
            new_name='imma',
        ),
    ]
