# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0003_auto_20170526_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='imma',
            field=models.CharField(max_length=25, verbose_name='Vehicule'),
        ),
    ]
