# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0008_auto_20170526_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='imma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Carnets', to='parcauto.Vehicule'),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='vehicules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparations', to='parcauto.Vehicule'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='carnets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='parcauto.Carnet'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='vehicules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='parcauto.Vehicule'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='carnets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='parcauto.Carnet'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modeles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='parcauto.Modele'),
        ),
    ]
