# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0012_auto_20170526_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='dateFinTravaux',
            field=models.DateTimeField(),
        ),
    ]
