# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0015_auto_20170526_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='garages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='parcauto.Garage'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='carburant',
            field=models.CharField(max_length=25, verbose_name='Carburant'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='marqueMod',
            field=models.CharField(max_length=25, verbose_name='Marque du model'),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='dateAccident',
            field=models.DateField(verbose_name="Date de l'accidnet"),
        ),
    ]
