# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0018_auto_20170526_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparation',
            name='garages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raparations', to='parcauto.Garage'),
        ),
    ]
