# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcauto', '0019_reparation_garages'),
    ]

    operations = [
        migrations.AddField(
            model_name='modele',
            name='couleur',
            field=models.CharField(default='blanc', max_length=25, verbose_name='Couleur du model'),
        ),
    ]
